# Generated by Django 3.1.1 on 2020-09-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicApp', '0003_tbl_teachers_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_teachers',
            name='email',
            field=models.CharField(default='......', max_length=30),
        ),
    ]
