# Generated by Django 3.1.1 on 2020-09-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicApp', '0006_tbl_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_student',
            name='gender',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='tbl_teachers',
            name='gender',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='tbl_student',
            name='admisionno',
            field=models.IntegerField(default='lastname', max_length=20),
        ),
    ]
