# Generated by Django 3.1.1 on 2020-09-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicApp', '0007_auto_20200922_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_teachers',
            name='type',
            field=models.CharField(max_length=10),
        ),
    ]
