# Generated by Django 3.1.1 on 2020-09-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicApp', '0008_auto_20200922_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_questin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('clas', models.IntegerField(max_length=5)),
                ('division', models.CharField(max_length=5)),
                ('questin', models.CharField(max_length=200)),
                ('ldate', models.CharField(max_length=20)),
            ],
        ),
    ]
