# Generated by Django 3.0.5 on 2020-09-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicApp', '0011_auto_20200922_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=20)),
            ],
        ),
    ]
