# Generated by Django 3.0.5 on 2020-09-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicApp', '0012_tbl_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_message',
            name='rid',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
