# Generated by Django 3.0.5 on 2020-09-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicApp', '0013_tbl_message_rid'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
