# Generated by Django 3.0.5 on 2020-09-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicApp', '0015_tbl_contact_rps'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_answers',
            name='mark',
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
